### ISSUE TITLE
无法访问org.jnetpcap.internal.NonSealedPcap

### ISSUE THREAD

**Issue by cq1982** [slytechs-repos/jnetpcap#32]
package com.slytechs.jnetpcap.examples;

import org.jnetpcap.PcapException;

import com.slytechs.jnetpcap.pro.PcapPro;
import com.slytechs.protocol.Packet;
import com.slytechs.protocol.meta.PacketFormat;
import com.slytechs.protocol.runtime.util.HexStrings;

public class CaptureVariedTraffic {
	private final String PCAP_FILE = "/bao/cheliangbukong.new.pcap";

	public static void main(String[] args) throws PcapException {
		new CaptureVariedTraffic().main();
	}

	void main() throws PcapException {

		try (var pcap = PcapPro.openOffline(PCAP_FILE)) {

			pcap.setPacketFormatter(new PacketFormat());

			int FRAME_NO = 400;
			pcap.loop(FRAME_NO + 1, this::nextPacket, FRAME_NO);
			
			pcap.loop(1, this::nextPacket, FRAME_NO);
		}

	}

	private void nextPacket(int frameNo, Packet packet) {
		
		System.out.println(packet.descriptor());
		
		System.out.println(HexStrings.toHexDump(packet.descriptor().buffer()));

		System.out.print(packet);
	}

}

CaptureVariedTraffic.java:41:32，就是PcapPro.openOffline这一行

java: 无法访问org.jnetpcap.internal.NonSealedPcap
  找不到org.jnetpcap.internal.NonSealedPcap的类文件

**Comment by slytechs-repos** [comment]
Can you explain please what the problem is you are trying to report? I do not see an error/exception in here.
