### ISSUE TITLE
Exception in example test

### ISSUE THREAD

**Issue by Okitask** [slytechs-repos/jnetpcap#33]
When i try the example:

`

public class MAIN {

	public static void main(String[] args) throws PcapException {

		/* raw bytes of our packet, spaces ignored */
		final String ETHERNET = "0026622f4787 001d60b30184 0800";
		final String IPv4 = "4500003ccb5b4000400628e4 c0a8FD05 c0a8FD06";
		final String TCP = "e14e00508e50190100000000a00216d08f470000020405b40402080a0021d25a0000000001030307";
		final byte[] packetBytes = PcapUtils.parseHexString(ETHERNET + IPv4 + TCP);

		List<PcapIf> devices = Pcap.findAllDevs();

		try (Pcap pcap = Pcap.create(devices.get(0))) {
			pcap.activate();

			/* Transmit our packet */
			pcap.sendPacket(packetBytes);
		}

}
}`

 i got :
`Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateExc
eption: can not invoke native C function 'pcap_findalldevs(AA)I'
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.internal.ForeignDowncall.invokeInt(F
oreignDowncall.java:93)
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.Pcap0_7.findAllDevs(Pcap0_7.java:195
)
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.Pcap.findAllDevs(Pcap.java:1063)
	at jnetpcap22/jnetpcap22.MAIN.main(MAIN.java:20)
Caused by: java.lang.IllegalStateException: can not invoke native C function 'pc
ap_findalldevs(AA)I'
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.internal.ForeignDowncall.handle(Fore
ignDowncall.java:64)
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.internal.ForeignDowncall.invokeInt(F
oreignDowncall.java:91)
	... 3 more
Caused by: java.util.NoSuchElementException: native C symbol "pcap_findalldevs" 
not found
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.internal.ForeignInitializer.resolveS
ymbol(ForeignInitializer.java:358)
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.internal.ForeignInitializer.downcall
(ForeignInitializer.java:298)
	at org.jnetpcap@2.0.0-alpha.2/org.jnetpcap.Pcap0_7.<clinit>(Pcap0_7.java:76)
	... 2 more`

**Comment by slytechs-repos** [comment]
Its not finding the native `libpcap.so` library. You need to specify the location for you system using `-Djava.library.path=(DIRECTORY PATH)` where its located on your system.

**Comment by Okitask** [comment]
Thank you  for response. I already have this in my VM arguments: 
`
-Djava.library.path=C:\Windows\SysWOW64 --enable-native-access=org.jnetpcap --enable-preview`
I have Npcap 1.74

**Comment by Okitask** [comment]
Npcap default dll dir: C:\Windows\System32\Npcap
Thank you

**Comment by slytechs-repos** [comment]
Its not finding the `npcap.dll` file in `C:\Windows\SysWOW64`. Try the path `-Djava.library.path="C:\Windows\System32"` as resolved per Issue #26 . I'm going to integerate all of these different paths as defaults to help with the startup. There are a handfull of paths it can try on its own. Look for a feature branch and pull request tracking it.
