### ISSUE TITLE
How do I obtain the payload Data in the TCP layer？

### ISSUE THREAD

**Issue by iamfuqiang** [slytechs-repos/jnetpcap#40]
Hello，Bro
I'm just learning how to use this library and I'm having some problems
I want to extract the TCPpayload from the captured data in wireshark and wrote some code that mimicked the sample code on github but was not very effective
_https://github.dev/slytechs-repos/jnetpcap-examples_  example_3

In the last output array, starting from the 57th byte is the payload of TCP, but I don't know what the first 56 bytes are. How can I directly extract the data I want from the MemorySegment packet?
I would appreciate it if you would reply at your leisure
`PcapUtils.toHexCurleyString(array, 56, array.length - 56)`

```java
void main() throws PcapException {
        /* Pcap capture file to read */
        final String PCAP_FILE = "/Users/fuqiang/IdeaProjects/Study/java-base/code-test/wireshark/shark-001.pcapng";

        /* Make sure we have a compatible Pcap runtime installed */
        Pcap.checkPcapVersion(Pcap.VERSION);

        /* Automatically close Pcap resource when done */
        try (PcapPro pcap = PcapPro.openOffline(PCAP_FILE)) {

            /* Compile packet filter to capture TCP packets only */
            BpFilter filter = pcap.compile("tcp dst port 7090", true);

            /* Set our packet filter and start the capture */
            pcap.setFilter(filter);

            /* Number of packets to capture */
            final int PACKET_COUNT = 10;

            /* Send packets to handler. The generic user parameter can be of any type. */
            pcap.dispatch(PACKET_COUNT, this::nextPacket, "Example 3");
        }
    }

    /** Our packet handler */
    void nextPacket(String user, MemorySegment hdr, MemorySegment packet) {

        PcapHeader header = new PcapHeader(hdr);
        byte[] hdrs = MemorySegment.ofAddress(hdr.address(), header.headerLength(), hdr.session())
                .toArray(ValueLayout.JAVA_BYTE);
        // MemorySegment contains packet data, accessible using new java's FF API
        byte[] array = MemorySegment
                .ofAddress(packet.address(), header.captureLength(), packet.session())
                .toArray(ValueLayout.JAVA_BYTE);

        System.out.printf("hdrs = %s  | pkgs = %s %n",
                PcapUtils.toHexCurleyString(hdrs, 0, hdrs.length),
                PcapUtils.toHexCurleyString(array, 0, array.length));
        System.out.printf("%s: timestamp=%s, wirelen=%-4d caplen=%-4d load=%s  headerlen=%s %s %n ",
                user,
                Instant.ofEpochMilli(header.toEpochMilli()),
                header.wireLength(),
                header.captureLength(),
                array.length,
                header.headerLength(),
                PcapUtils.toHexCurleyString(array, 56, array.length - 56)
                );
    }
```

**Comment by slytechs-repos** [comment]
The entire packet is in the byte array. So the 1st 56 bytes are at the beginning of your array. 

`PcapUtils.toHexCurleyString(array, 0, 57)`

**Comment by iamfuqiang** [comment]
> The entire packet is in the byte array. So the 1st 56 bytes are at the beginning of your array.
> 
> `PcapUtils.toHexCurleyString(array, 0, 57)`

Thank you for your answer, But I'm sorry, maybe I didn't get that right. What I want now is to extract the actual transmission data from the TCP layer, ignore SYN packets and ACK packets and other useless messages in the transmission process Is there a neat and elegant way to call it directly instead of using byte subscripts?
The pseudocode is as follows
```java
if (packet instance of tcp && packet.hasPayload()) {
    byte[] payload = packet.getPayload();
    file.write(payload);
}
```

**Comment by slytechs-repos** [comment]
I think what you want is jNetPcap-Pro library. It is protocol enabled and much friendlier to use. It has the TCP header definition you are looking for.

> note: The base pcap library just lets you work with raw packets. It is designed to correctly instrument the native libpcap library which comes with no higher level protocol functions.

**Comment by iamfuqiang** [comment]
> 我想你想要的是 jNetPcap-Pro 库。它启用了协议并且使用起来更加友好。它具有您要查找的 TCP 标头定义。
> 
> > 注意：基础 pcap 库只允许您处理原始数据包。它旨在正确检测没有更高级别协议功能的本机 libpcap 库。

Thank you very much for your answer. I will go to learn JnetPcap Pro
