### ISSUE TITLE
Can not invoke native C function when run on Mac

### ISSUE THREAD

**Issue by qqeric2** [slytechs-repos/jnetpcap#9]
Hi, I just follow the instructions and build the jnetpcap v2 with Java 19. Unfortunately, I always get errors of "can not invoke native C function XXX" in the tests. 

I set the VM option in Intellij as "-Djava.library.path=/usr/local/Cellar/libpcap/1.10.3/lib --enable-native-access=org.jnetpcap --enable-preview"

I install the libpcap with homebrew. Here is what I have in the lib folder: "libpcap.1.10.3.dylib", "libpcap.a", "pkgconfig", "libpcap.A.dylib", "libpcap.dylib". 

If possible would you mind telling me what's wrong with my running configurations that make it unable to invoke native C functions? Thanks.

**Comment by slytechs-repos** [comment]
I'm getting the same thing on my end. System.loadLibrary("pcap") is not finding the native dynamic library on MacOS even with the proper LD_LIBRARY_PATH.

I will figure this out and checkin a patch. I will also add a way to override the behavior via a set of environment variables  and system property/commands line args to allow alternative methods of loading the library such as System.load(${ABSOLUTE_PATH}), etc..

**Comment by slytechs-repos** [comment]
You can use the following work around to get it going, while I figure out a permanent solution. Somewhere in your example, you need to load the native pcap library with absolute path. The default "LibraryPolicy" will try the currently predifined ways of loading 'pcap', but as long as its loaded before "Pcap.java" class is referenced, all the neccessary native symbols will be loaded. So do this somewhere, before 'Pcap' is referenced and it should work.
```java
void main() {
   System.load("/usr/local/Cellar/libpcap/1.10.3/lib/libpcap.dylib");

  // Your sample code
}
```

**Comment by qqeric2** [comment]
@slytechs-repos Thanks for your quick response. This code successfully fixes the problem.

**Comment by slytechs-repos** [comment]
Glad to hear it. I have also updated the maven build pom.xml with multiple profiles for each platform and architecture. It selects automatically the proper properties to run unit tests.

I will check those changes in after a bit more testing.
